MQTT:
    broker: tcp://localhost:1883
    clientId: go-mqtt-client
    qos: 1
    connectionInterval: 3s
    maxRetry: 0
    maxDelay: 1m0s
    #username: username
    #password: password
DB:
    DbURL: postgres://user:password@localhost:5432/mydb?sslmode=disable
    query_timeout_read: 5s
    query_timeout_write: 2s
    topicRefreshingInterval: 60s
    connectionInterval: 3s
    maxRetry: 0
    maxDelay: 1m0s
Workers:
    number: 5